### ISSUE TITLE
Added an ERC20 Token from Private Parity Network (Correct ABI, Contract Address, Etherchain Light Working)

### ISSUE THREAD

**Issue by alexacostarua** [gobitfly/erc20-explorer#8]
Exporter initialized, waiting for historical events...
Historical events received
Exporting log: 73_0_0
73_0_0 already exported!
All historical logs processed
Exporting balance of undefined
/home/user1/erc20explorer/node_modules/web3/lib/web3/function.js:71
        throw errors.InvalidNumberOfSolidityArgs();
        ^

Error: Invalid number of arguments to Solidity function
    at Object.InvalidNumberOfSolidityArgs (/home/user1/erc20explorer/node_modules/web3/lib/web3/errors.js:25:16)
    at SolidityFunction.validateArgs (/home/user1/erc20explorer/node_modules/web3/lib/web3/function.js:71:22)
    at SolidityFunction.toPayload (/home/user1/erc20explorer/node_modules/web3/lib/web3/function.js:87:10)
    at SolidityFunction.call (/home/user1/erc20explorer/node_modules/web3/lib/web3/function.js:128:24)
    at SolidityFunction.execute (/home/user1/erc20explorer/node_modules/web3/lib/web3/function.js:257:22)
    at exporter.self.exportBalance (/home/user1/erc20explorer/services/exporter.js:107:19)
    at /home/user1/erc20explorer/services/exporter.js:67:12
    at /home/user1/erc20explorer/node_modules/async/dist/async.js:3110:16
    at replenish (/home/user1/erc20explorer/node_modules/async/dist/async.js:1011:17)
    at /home/user1/erc20explorer/node_modules/async/dist/async.js:1016:9
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! erc20-explorer@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the erc20-explorer@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user1/.npm/_logs/2018-08-09T12_52_41_579Z-debug.log
----------------------------------------------------------------------------------------------------------------------------------
Full Log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle erc20-explorer@0.0.0~prestart: erc20-explorer@0.0.0
6 info lifecycle erc20-explorer@0.0.0~start: erc20-explorer@0.0.0
7 verbose lifecycle erc20-explorer@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle erc20-explorer@0.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user1/erc20explorer/node_modules/.bin:/home/user1/bin:/home/user1/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle erc20-explorer@0.0.0~start: CWD: /home/user1/erc20explorer
10 silly lifecycle erc20-explorer@0.0.0~start: Args: [ '-c', 'node ./bin/www' ]
11 silly lifecycle erc20-explorer@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle erc20-explorer@0.0.0~start: Failed to exec start script
13 verbose stack Error: erc20-explorer@0.0.0 start: `node ./bin/www`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid erc20-explorer@0.0.0
15 verbose cwd /home/user1/erc20explorer
16 verbose Linux 4.4.0-31-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error erc20-explorer@0.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the erc20-explorer@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
----------------------------------------------------------------------------------------------------------------------------------
Thanks.

**Comment by Kayryu** [comment]
@alexacostarua  how deal with it ?  I meet the same problem 。Thanks

**Comment by fty48jj19** [comment]
e  vc tem procura em editorial  de codigos ,
